apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ga-practice
  name: ga-practice
  namespace: practice
spec:
  containers:
  - image: nginx
    name: ga-practice
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
